name: Deploy to ECR

on:
 
  push:
    branches: [ trial ]

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
        
 #ecs service


     
 
    
      #run:
        #aws ecs describe-task-definition --task-definition task- --query taskDefinition > task-definition.json
       # aws ecs create-service --cluster test --service-name service --task-definition arn:aws:ecs:us-east-1:190177667055:task-definition/task-:12 --desired-count 2 --launch-type FARGATE

       # aws ecs run-task --cluster tmp3 --task-definition arn:aws:ecs:us-east-1:190177667055:task-definition/task-:12
      
  
      
      
      
    - name: Update ECS service
      run: |
          aws ecs update-service \
          --cluster test \
          --service services \
          --task-definition arn:aws:ecs:us-east-1:190177667055:task-definition/task- \
          --force-new-deployment      
      

        




  #  - name: Remove registeredAt and registeredBy from JSON file
    #  run: jq 'del(.registeredAt, .registeredBy)' task-definition.json > task-definition.json

    

        


 




